// Code generated by counterfeiter. DO NOT EDIT.
package servicesfakes

import (
	"sync"

	jwt "github.com/golang-jwt/jwt/v4"
	"github.com/nathaliaguayos/msg-receiver/internal/services"
)

type FakeJWTService struct {
	GenerateTokenStub        func(string) (string, error)
	generateTokenMutex       sync.RWMutex
	generateTokenArgsForCall []struct {
		arg1 string
	}
	generateTokenReturns struct {
		result1 string
		result2 error
	}
	generateTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ValidateTokenStub        func(string) (*jwt.Token, error)
	validateTokenMutex       sync.RWMutex
	validateTokenArgsForCall []struct {
		arg1 string
	}
	validateTokenReturns struct {
		result1 *jwt.Token
		result2 error
	}
	validateTokenReturnsOnCall map[int]struct {
		result1 *jwt.Token
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJWTService) GenerateToken(arg1 string) (string, error) {
	fake.generateTokenMutex.Lock()
	ret, specificReturn := fake.generateTokenReturnsOnCall[len(fake.generateTokenArgsForCall)]
	fake.generateTokenArgsForCall = append(fake.generateTokenArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GenerateTokenStub
	fakeReturns := fake.generateTokenReturns
	fake.recordInvocation("GenerateToken", []interface{}{arg1})
	fake.generateTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJWTService) GenerateTokenCallCount() int {
	fake.generateTokenMutex.RLock()
	defer fake.generateTokenMutex.RUnlock()
	return len(fake.generateTokenArgsForCall)
}

func (fake *FakeJWTService) GenerateTokenCalls(stub func(string) (string, error)) {
	fake.generateTokenMutex.Lock()
	defer fake.generateTokenMutex.Unlock()
	fake.GenerateTokenStub = stub
}

func (fake *FakeJWTService) GenerateTokenArgsForCall(i int) string {
	fake.generateTokenMutex.RLock()
	defer fake.generateTokenMutex.RUnlock()
	argsForCall := fake.generateTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJWTService) GenerateTokenReturns(result1 string, result2 error) {
	fake.generateTokenMutex.Lock()
	defer fake.generateTokenMutex.Unlock()
	fake.GenerateTokenStub = nil
	fake.generateTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTService) GenerateTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.generateTokenMutex.Lock()
	defer fake.generateTokenMutex.Unlock()
	fake.GenerateTokenStub = nil
	if fake.generateTokenReturnsOnCall == nil {
		fake.generateTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.generateTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTService) ValidateToken(arg1 string) (*jwt.Token, error) {
	fake.validateTokenMutex.Lock()
	ret, specificReturn := fake.validateTokenReturnsOnCall[len(fake.validateTokenArgsForCall)]
	fake.validateTokenArgsForCall = append(fake.validateTokenArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateTokenStub
	fakeReturns := fake.validateTokenReturns
	fake.recordInvocation("ValidateToken", []interface{}{arg1})
	fake.validateTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeJWTService) ValidateTokenCallCount() int {
	fake.validateTokenMutex.RLock()
	defer fake.validateTokenMutex.RUnlock()
	return len(fake.validateTokenArgsForCall)
}

func (fake *FakeJWTService) ValidateTokenCalls(stub func(string) (*jwt.Token, error)) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = stub
}

func (fake *FakeJWTService) ValidateTokenArgsForCall(i int) string {
	fake.validateTokenMutex.RLock()
	defer fake.validateTokenMutex.RUnlock()
	argsForCall := fake.validateTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJWTService) ValidateTokenReturns(result1 *jwt.Token, result2 error) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = nil
	fake.validateTokenReturns = struct {
		result1 *jwt.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTService) ValidateTokenReturnsOnCall(i int, result1 *jwt.Token, result2 error) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = nil
	if fake.validateTokenReturnsOnCall == nil {
		fake.validateTokenReturnsOnCall = make(map[int]struct {
			result1 *jwt.Token
			result2 error
		})
	}
	fake.validateTokenReturnsOnCall[i] = struct {
		result1 *jwt.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeJWTService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.generateTokenMutex.RLock()
	defer fake.generateTokenMutex.RUnlock()
	fake.validateTokenMutex.RLock()
	defer fake.validateTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJWTService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.JWTService = new(FakeJWTService)
